In [1]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
!pip install category_encoders

In [3]:
os.chdir(r'C:\Users\nanda\employee-attrition')

In [4]:
df_left = pd.read_csv('employee_who_left.csv')

In [5]:
df_left.shape

(3571, 10)

In [6]:
df_left.head()

Emp ID  satisfaction_level  last_evaluation  number_project  \
0       1                0.38             0.53               2   
1       2                0.80             0.86               5   
2       3                0.11             0.88               7   
3       4                0.72             0.87               5   
4       5                0.37             0.52               2   

   average_montly_hours  time_spend_company  Work_accident  \
0                   157                   3              0   
1                   262                   6              0   
2                   272                   4              0   
3                   223                   5              0   
4                   159                   3              0   

   promotion_last_5years   dept  salary  
0                      0  sales     low  
1                      0  sales  medium  
2                      0  sales  medium  
3                      0  sales     low  
4                      0  sales     low

In [7]:
df_left_copy = df_left.copy()

In [8]:
df_left_copy['target'] = 1

In [9]:
df_emp = pd.read_csv('existing_employee.csv')

In [10]:
df_emp.head()

Emp ID  satisfaction_level  last_evaluation  number_project  \
0    2001                0.58             0.74               4   
1    2002                0.82             0.67               2   
2    2003                0.45             0.69               5   
3    2004                0.78             0.82               5   
4    2005                0.49             0.60               3   

   average_montly_hours  time_spend_company  Work_accident  \
0                   215                   3              0   
1                   202                   3              0   
2                   193                   3              0   
3                   247                   3              0   
4                   214                   2              0   

   promotion_last_5years   dept salary  
0                      0  sales    low  
1                      0  sales    low  
2                      0  sales    low  
3                      0  sales    low  
4                      0  sales    low

In [11]:
df_emp.shape

(11428, 10)

In [12]:
df_emp_copy = df_emp.copy()

In [13]:
df_emp_copy['target'] = 0

In [14]:
# final_df.append(df_emp_copy, ignore_index=True)
final_df = pd.concat([df_left_copy,df_emp_copy])

In [15]:
final_df.shape

(14999, 11)

In [16]:
final_df.columns

Index(['Emp ID', 'satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years', 'dept', 'salary', 'target'],
      dtype='object')

In [17]:
final_df =final_df.drop('Emp ID',axis=1)

In [18]:
final_df.tail()

satisfaction_level  last_evaluation  number_project  \
11423                0.90             0.55               3   
11424                0.74             0.95               5   
11425                0.85             0.54               3   
11426                0.33             0.65               3   
11427                0.50             0.73               4   

       average_montly_hours  time_spend_company  Work_accident  \
11423                   259                  10              1   
11424                   266                  10              0   
11425                   185                  10              0   
11426                   172                  10              0   
11427                   180                   3              0   

       promotion_last_5years        dept salary  target  
11423                      1  management   high       0  
11424                      1  management   high       0  
11425                      1  management   high       0  
11426                      1   marketing   high       0  
11427                      0          IT    low       0

In [19]:
# shuffling dataframe

In [20]:
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [21]:
final_df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.73             0.86               4                   133   
1                0.21             0.77               6                   215   
2                0.60             0.98               4                   195   
3                0.41             0.47               2                   154   
4                0.77             0.87               5                   257   

   time_spend_company  Work_accident  promotion_last_5years         dept  \
0                   3              0                      0    technical   
1                   4              0                      0        sales   
2                   3              0                      0      support   
3                   3              0                      0        sales   
4                   2              0                      0  product_mng   

   salary  target  
0    high       0  
1  medium       0  
2  medium       0  
3     low       1  
4  medium       0

In [22]:
final_df['dept'].value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: dept, dtype: int64

In [23]:
final_df['salary'].value_counts()

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [24]:
final_df_wo= final_df.copy()

In [25]:
# !pip install category_encoders

In [26]:
categorical_cols = ['salary','dept']

############################################
from category_encoders import one_hot
ohe = one_hot.OneHotEncoder(use_cat_names=True)
array_hot_encoded = ohe.fit_transform(final_df[categorical_cols])
data_hot_encoded = pd.DataFrame(array_hot_encoded)
data_other_cols = final_df.drop(columns=categorical_cols)
# # #Concatenate the two dataframes : 
final_df = pd.concat([data_hot_encoded, data_other_cols], axis=1)

In [27]:
# Dumping the transformer to an external pickle file
import joblib
joblib.dump(ohe, 'clean_ohe.pkl')

['clean_ohe.pkl']

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
final_df.head(2)

salary_high  salary_medium  salary_low  dept_technical  dept_sales  \
0            1              0           0               1           0   
1            0              1           0               0           1   

   dept_support  dept_product_mng  dept_IT  dept_RandD  dept_marketing  ...  \
0             0                 0        0           0               0  ...   
1             0                 0        0           0               0  ...   

   dept_management  dept_hr  satisfaction_level  last_evaluation  \
0                0        0                0.73             0.86   
1                0        0                0.21             0.77   

   number_project  average_montly_hours  time_spend_company  Work_accident  \
0               4                   133                   3              0   
1               6                   215                   4              0   

   promotion_last_5years  target  
0                      0       0  
1                      0       0  

[2 rows x 21 columns]

In [30]:
final_df.isnull().sum()

salary_high              0
salary_medium            0
salary_low               0
dept_technical           0
dept_sales               0
dept_support             0
dept_product_mng         0
dept_IT                  0
dept_RandD               0
dept_marketing           0
dept_accounting          0
dept_management          0
dept_hr                  0
satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
promotion_last_5years    0
target                   0
dtype: int64

In [31]:
final_df.columns

Index(['salary_high', 'salary_medium', 'salary_low', 'dept_technical',
       'dept_sales', 'dept_support', 'dept_product_mng', 'dept_IT',
       'dept_RandD', 'dept_marketing', 'dept_accounting', 'dept_management',
       'dept_hr', 'satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years', 'target'],
      dtype='object')

In [32]:
X = final_df.drop(['target'], axis=1)
y = final_df['target']

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [34]:
print(f'X_train shape{X_train.shape}')
print(f'X_test shape{X_test.shape}')
print('*'*25)
print(f'y_train shape{y_train.shape}')
print(f'y_test shape{y_test.shape}')

X_train shape(10499, 20)
X_test shape(4500, 20)
*************************
y_train shape(10499,)
y_test shape(4500,)


# Baseline model(Decision Tree)

In [35]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model = model.fit(X_train.values, y_train)
 
y_pred = model.predict(X_test)
print(y_pred)

[1 1 0 ... 0 0 0]


In [36]:
from sklearn.metrics import confusion_matrix 

def get_metrics(true_values, pred_values):
    print('Confusion matrix \n')
    cm= confusion_matrix(true_values, pred_values) 
    print(cm)
    print('*'*30)
    print ("Accuracy : ",accuracy_score(true_values, pred_values)*100)
    print('*'*30)
    print("Report : \n",classification_report(true_values, pred_values))
    

In [37]:
from sklearn.metrics import accuracy_score, classification_report

get_metrics(y_test,y_pred)

Confusion matrix 

[[3402   49]
 [  34 1015]]
******************************
Accuracy :  98.15555555555555
******************************
Report : 
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      3451
           1       0.95      0.97      0.96      1049

    accuracy                           0.98      4500
   macro avg       0.97      0.98      0.97      4500
weighted avg       0.98      0.98      0.98      4500



# RandomForest

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model = rf_model.fit(X_train.values, y_train)
 
rf_y_pred = rf_model.predict(X_test)
print(rf_y_pred)

[1 1 0 ... 0 0 0]


In [39]:
get_metrics(y_test,rf_y_pred)

Confusion matrix 

[[3440   11]
 [  36 1013]]
******************************
Accuracy :  98.95555555555555
******************************
Report : 
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      3451
           1       0.99      0.97      0.98      1049

    accuracy                           0.99      4500
   macro avg       0.99      0.98      0.99      4500
weighted avg       0.99      0.99      0.99      4500



In [40]:
# saving model in picle format

In [41]:
import pickle
pickle.dump(rf_model, open('emp_rf.pkl','wb'))

# Model Inference

In [42]:
 # loading the model

In [43]:
inf_model = pickle.load(open('emp_rf.pkl','rb'))

In [44]:
# input to the models
print('Input Values')
print('*'*20)
print(X_train.iloc[2])
print('*'*20)
print('target \n ', y_train.iloc[2])

Input Values
********************
salary_high                0.00
salary_medium              0.00
salary_low                 1.00
dept_technical             1.00
dept_sales                 0.00
dept_support               0.00
dept_product_mng           0.00
dept_IT                    0.00
dept_RandD                 0.00
dept_marketing             0.00
dept_accounting            0.00
dept_management            0.00
dept_hr                    0.00
satisfaction_level         0.85
last_evaluation            0.89
number_project             4.00
average_montly_hours     221.00
time_spend_company         5.00
Work_accident              0.00
promotion_last_5years      0.00
Name: 1572, dtype: float64
********************
target 
  1


In [45]:
pred_results = inf_model.predict(np.array(X_train.iloc[0]).reshape(1,-1))
pred_results[0]

0

In [46]:
pred_results = inf_model.predict(np.array(X_train.iloc[2]).reshape(1,-1))
pred_results[0]

1

# Predict model

In [47]:
def cleanData(df,cat_columns, ohe_fl, model):
    
    ''' 
    Clean the dataframe, arrange the dataframe into 
    model required format
    Input:   df(dataframe)
             cat_columns: categorical columns(['salary','dept'])
             ohe_fl: onehotEncode model
             model: predictive model
    Output: preduction result
    '''
    
    loaded_ce_dummies = ohe_fl.transform(df[cat_columns])
    
    data_other_cols = df.drop(columns=cat_columns)
    # # #Concatenate the two dataframes
    pred_df = pd.concat([loaded_ce_dummies, data_other_cols], axis=1)
    
    pred_res = model.predict(pred_df.values)
    
    return pred_res[0]
    

In [48]:
input_data = dict(final_df_wo.iloc[3][:-1])

In [49]:
input_data

{'satisfaction_level': 0.41,
 'last_evaluation': 0.47,
 'number_project': 2,
 'average_montly_hours': 154,
 'time_spend_company': 3,
 'Work_accident': 0,
 'promotion_last_5years': 0,
 'dept': 'sales',
 'salary': 'low'}

In [50]:
ddf = pd.DataFrame(input_data, index=[0])

In [58]:
# ddf.to_csv('test_file.csv')

In [51]:
ce_ohe = joblib.load('clean_ohe.pkl')
model_pkl = joblib.load('emp_rf.pkl')

In [52]:
cleanData(ddf,['salary','dept'], ce_ohe, model_pkl)

1

In [53]:
final_df.head()

salary_high  salary_medium  salary_low  dept_technical  dept_sales  \
0            1              0           0               1           0   
1            0              1           0               0           1   
2            0              1           0               0           0   
3            0              0           1               0           1   
4            0              1           0               0           0   

   dept_support  dept_product_mng  dept_IT  dept_RandD  dept_marketing  ...  \
0             0                 0        0           0               0  ...   
1             0                 0        0           0               0  ...   
2             1                 0        0           0               0  ...   
3             0                 0        0           0               0  ...   
4             0                 1        0           0               0  ...   

   dept_management  dept_hr  satisfaction_level  last_evaluation  \
0                0        0                0.73             0.86   
1                0        0                0.21             0.77   
2                0        0                0.60             0.98   
3                0        0                0.41             0.47   
4                0        0                0.77             0.87   

   number_project  average_montly_hours  time_spend_company  Work_accident  \
0               4                   133                   3              0   
1               6                   215                   4              0   
2               4                   195                   3              0   
3               2                   154                   3              0   
4               5                   257                   2              0   

   promotion_last_5years  target  
0                      0       0  
1                      0       0  
2                      0       0  
3                      0       1  
4                      0       0  

[5 rows x 21 columns]

In [54]:
final_df_wo.loc[0].values

array([0.73, 0.86, 4, 133, 3, 0, 0, 'technical', 'high', 0], dtype=object)

In [55]:
len(final_df.loc[0].values)

21

In [56]:
inf_model.predict(np.array(X_train.iloc[2]).reshape(1,-1))

array([1], dtype=int64)